language: node_js
node_js:
  - "8.9.1"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run build-prod
  - cd dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
